import { Director } from '@/entities/Director/module/types/Director';
import { Rating } from '@/entities/Rating/model/types/rating';

export type Card = {
  _id: string;
  posterImage: string;
  backgroundImage: string;
  reviews: string[];
  name: string;
  secondName: string;
  ratings: Rating[];
  userLike: number;
  userDislike: number;
  favorites: number;
  year: number;
  country: string[];
  slogan: string;
  directors: Director[];
  screenwriters: string[];
  producers: string[];
  operators: string[];
  composers: string[];
  artists: string[];
  editors: string[];
  genres: string[];
  collecting: number;
  premiereInWorld: string;
  premiereInRussia: string;
  age: number;
  duration: number;
  production: string[];
  specialEffects: string[];
  dubbingStudios: string[];
  persons: string[];
  trailers: string[];
  awards: string[];
  posters: string[];
  shots: string[];
  sequelAndPrequels: string[];
  quotes: string[];
  seemFilms: string[];
  description: string;
};
