export type Person = {
  _id: string;
  name: string;
  englishName: string;
  avatarImage: string;
  linkToBiography: string;
  career: string[];
  height: string;
  birthday: string[];
  bornPlace: string;
  genres: string[];
  totalCountOfFilmsAndYears: string[];
  favorites: number;
  awards: string[];
  bestFilms: string[];
  lastNews: string[];
  photos: string[];
  films: string[];
  comments: string[];
};
